### ISSUE TITLE
rewrite sub process execution and capture using cli_script

### ISSUE THREAD

**Issue by bsutton** [onepub-dev/dcli#140]
nweiz@google.com has proposed using cli_script to replace the internal processing of spawned subcommands.

If we are doing a (overdue) rewrite then what the objectives that we want to achive.

1) backwards compatibility with existing api (as far is reasonalby possible)
2) Improvements to Progress - currently its easy to mis-use a Progress
3) streaming - look at the problems I was trying to solve with the repl demo.
4) separation of stdout/stderr
5) capture printerr using the zone as well as print (is this even possible).
6) support for terminal/detached/ privileged modes.
7) fully utilise cli_scripts pipelining
8) Review the use of Settings().verbose and general logging.
9) Glob expansion of cmd args.

Do we make function such as copy full async or is using the underlying copySync method ok.

**Comment by bsutton** [comment]
How do we deal with discrepancies in the calling conventions.

Dcli uses either cmdLine or cmd and args, 
cli_script uses cmdAndArgs with args.

**Comment by bsutton** [comment]
Where do we start?
Do we re-write the existing sync run/start .. methods to use cli_script. Is there any advantage.

What does the core async api look like? 
Does it expose the cli_script Script interface?
Do we still expose the existing run/start/toList progress interfaces in the async version or are these only sync versions.
Ideally we want to make it easy to move between the sync and async version of the libraries.
This means we need consistent naming and argument conventions.

DCli has a Script class and cli_script has a Script class. This feels problematic.
Is it too late to rename the cli_script class Script to something else to remove this clash? Scriptable|Action|Operation|Step|Transform|Stage?
Is it viable to rename DCli Script class to DartScript - this is in line with the DartProject class.
 - this would be a breaking change as the DCli Script is fairly widely used.

**Comment by nex3** [comment]
> How do we deal with discrepancies in the calling conventions.
> 
> Dcli uses either cmdLine or cmd and args,
> cli_script uses cmdAndArgs with args.

It's probably a good idea to at least make sure the `cmdLine` calling convention uses the same syntax as `cmdAndArgs`. The nice thing about the `cmdAndArgs` format is that it has the fallback case of being like `cmdLine` if you want something terse, and being like `cmd` + `args` if you want to pass a bunch of dynamic args, and allowing you to mix and match otherwise.

> Where do we start?
> Do we re-write the existing sync run/start .. methods to use cli_script. Is there any advantage.

Even in sync mode, it could be useful to use the `cli_script` infrastructure + `waitFor` in order to get the automatic stdio capturing behavior.
 
> What does the core async api look like?
> Does it expose the cli_script Script interface?
> Do we still expose the existing run/start/toList progress interfaces in the async version or are these only sync versions.
> Ideally we want to make it easy to move between the sync and async version of the libraries.
> This means we need consistent naming and argument conventions.

One way to handle this would be to have `cli_script` *be* "the async version", and then have DCLI be a synchronous API on top of that (that also adds UX sugar like String extension methods). My hope is to get the `cli_script` API on its own usable enough in a pure async world that there wouldn't be a strong need for additional layers, although maybe that involves pulling in some more ideas from DCLI.

> DCli has a Script class and cli_script has a Script class. This feels problematic.
> Is it too late to rename the cli_script class Script to something else to remove this clash? Scriptable|Action|Operation|Step|Transform|Stage?
> Is it viable to rename DCli Script class to DartScript - this is in line with the DartProject class.
> * this would be a breaking change as the DCli Script is fairly widely used.

I noticed that, but since the DCLI one says it's "primarily for internal use" I didn't expect it to be widely used. I'm not entirely opposed to renaming `cli_script`'s `Script`, but since it's the heart of the package (and matches the package name) I'd really like to avoid doing so if possible. The only other name that really encapsulates the idea of "an abstract notion of a running entity with stdio and escape codes" is `Process`, and that's already taken by `dart:io`.

**Comment by passsy** [comment]
I'd love to see https://github.com/google/dart_cli_script be exposed via dcli. The sync api sometimes feels a bit limited when I explicitly want things to run in parallel.

The `Script.capture` API looks neat, great work @nex3. Although, I really like that dcli automatically captures and prints on non-zero exit.

I don't use the `Script` class, changing it at least wouldn't break my code 😉

**Comment by bsutton** [comment]
Notes from conversation with @nex3 

Look at existing start and startWithArgs to see if they can be enhanced to use the cmdArgs + args structure of cli_scripts.
If not discuss change cli_script to conform with hour start and startWithArgs work or provide wrappers for same so we end up with a consistent api.

Globs
- I forgot to mention globs in our discussion. Start and startWithArgs etc support glob expansion on linux/osx.
- cli_scripts probably needs to support this.
- also need to look at QArgs as quote processing is critical. Ideally cli_script should use the same functions or we need to wrap cli_script so that we pass arguments that have been processed by QArgs/Globs.

mode changes
 - we need to have cli_scripts support ProcessStartMode and both the terminal and detached modes. Need to have a look at how these affect access to stdout/stderr particularly with the detached mode as stdout/stderr aren't available.

flutter version - maybe a library within the async library.
- would be useful to make the library available to flutter users. 
- this may require a library within a library but hopefully we can make the dcli_async library flutter compliant.

Packaging
The aim is to end up with two packages
dcli
dcli_async

Both packages would use the same naming convertions
e.g.
copy would be called copy in both packages.

If you directly use the async library you can just directly call the async copy method.

If you are using the main dcli package then dcli would export the dcli_async package using a name space.
Perhaps dasync.  - I'm inclined to stay away from the 'async' name space as its more likely to be used by other packages.

So calls to the sync version of copy would be
`copy`
calls to the async version would be
`dasync.copy`

Look at renaming the DCli's Script class to DartScript
As the Script library is currently marked for internal use only we can probably safely rename the DCli Script class to DartScript.
The other option would be to go to DartLibrary as this is probably the correct name.

BS raised some concerns as to how do we deal with output, lines, check.
These names to quite match up with the existing dcli naming convention (toList, Process.exitCode)
Should these names be new string extensions?
Should they be changed to return a Progress?
Some experimentation will be need around this.

Timer.run
@nex3 went through how this works and indicated that it should be stable going forward and should provide consistent errors when users mis-use the api.

**Comment by nex3** [comment]
> Globs
> 
> * I forgot to mention globs in our discussion. Start and startWithArgs etc support glob expansion on linux/osx.
> * cli_scripts probably needs to support this.
> * also need to look at QArgs as quote processing is critical. Ideally cli_script should use the same functions or we need to wrap cli_script so that we pass arguments that have been processed by QArgs/Globs.

I can add support for globs to `cli_script`'s arg parsing. I'm looking through `parse_cli_command` and I see a few notable places where it looks like the behavior differs currently with `cli_script`'s:

* DCLI doesn't support backslash-escapes, whereas `cli_script` does. I think these are important for allowing users to write literal quotes, glob characters, and so on. Escapes also make it possible to implement `cli_script`'s `arg()` helper, which allowsan argument to be safely interpolated directly into a command string.
* I think DCLI will interpret quotes within words as creating a separate word, whereas `cli_script` will interpret them as part of the same word. `cli_script`'s behavior here matches shell behavior, and is fairly common when passing options that contain spaces (e.g. `git commit --message="foo bar"`).

Glob support brings up an interesting question, though: if we want to add the ability for Flutter users to make *everything* asynchronous, how do we handle `Glob.listSync()`? For `cli_pkg`, it's fine to do argument resolution asynchronously since everything is asynchronous anyway, but how do you want to handle that when the parsing needs to be synchronous?

> Packaging
> The aim is to end up with two packages
> dcli
> dcli_async

Do they need to be two packages, or can they just be two libraries within one package?

**Comment by bsutton** [comment]
@nex3 just an update.

I've finally managed to clear my plate of a number of other projects, so I should be able to start working on this full time this week.

**Comment by bsutton** [comment]
@nex3 I've finally published an early release of dcli_core which is purely Async.

It only has a limited no of the most common functions but I will migrate more functions over the coming weeks.

I've not started the work to integrate you package as yet but hopefully not too far off.

**Comment by passsy** [comment]
Are there still plans to use `cli_script` in `dcli_core`?

**Comment by bsutton** [comment]
Yes and no.
There are a number of impedance mis-matches between how cli_script works
and the aims of dcli_core.
I'm currently exploring a new api (currently called halfpipe) that leans on
design work in cli_scripts but is more inline with the way I want dcli to
work.

This work has been side tracked a little as I'm working on project
'minion', which is designed to provide similar functionality to the bash
'expect' tooling but in Dart.
I need minion to improve unit tests for dcli and onepub (https://onepub.dev)
(because I refuse to work with bash :)

Once I have Minion in a reasonable state I will get back to halfpipe.

**Comment by bsutton** [comment]
closed as not proceeding.  Halfpipe is the likely way forward
