### ISSUE TITLE
Bug pub get in this package

### ISSUE THREAD

**Issue by the-best-is-best** [onepub-dev/dcli#235]
Resolving dependencies...
Because dcli >=4.0.1-alpha.11 depends on dcli_terminal ^4.0.1-alpha.11 which doesn't match any versions, dcli >=4.0.1-alpha.11 is forbidden.

dcli_terminal not upload v 4.0.1-alpha.11  ??

**Comment by bsutton** [comment]
Yes had a problem with the release, will retry in that morning.

**Comment by Aniketkhote** [comment]
When will this problem be resolved? Our CLI application is currently not functioning due to an issue with the `waitFor` functionality.

**Comment by bsutton** [comment]
@Aniketkhote DCli is an open source project maintained by a single developer (me). So perhaps a better way of asking your question would be:

DCli is a critical piece of our infrastructure which isn't currently working, due to the waitFor issue. How can I help to get a new release out the door?

@Aniketkhote  Well thanks for asking and offering to help.

You can view the main discussion thread around this issue at:
https://github.com/onepub-dev/dcli/discussions/233

I've listed a number of tasks that need to be completed.
https://github.com/onepub-dev/dcli/wiki

If everyone pitches in an helps we can get a release out the door in no time.

**Comment by bsutton** [comment]
this should be resolved in 4.0.1-beta.a
