### ISSUE TITLE
Consider allowing APT dependencies.

### ISSUE THREAD

**Issue by bsutton** [onepub-dev/dcli#25]
Consider allowing apt dependencies.

Not certain how this would work for compiled scripts. We would need to inject some 'install' logic to install the apt dependencies on first run.

**Comment by julemand101** [comment]
Maybe instead make some kind of requirement header where you can specify that the script needs a list of commands/files exists on the machine and check for this requirements before the script are running. Maybe add some kind of optional description field for each requirement (or group of) which can be written to the user if the files are missing.

By doing that, it would be possible to make a more platform generic way to tell the user that a command and/or file are missing and the user needs to install a package for the script to be working.

I understand that doing something automatically would be "nice" but since dshell scripts are properly not running as root it would still require some amount of user interaction to install additional packages.

Also, by adding some kind of package manager logic you properly need to extend that to multiple package managers since there are a lot of them. Also, the name (and version) of packages are different on each Linux distribution.

So I think a more simple solution would be better here. :)

**Comment by bsutton** [comment]
I do agree there are lots of problems here and possibly no easy way to
solve them in an automated fashion.

Your ideas of doing an assert doing the clean is certainly interesting.

Nether suggestion is going to help with a compiled executable that is
copied to another machine.

I'm inclined to leave this issue until where get a few more pressing issues
resolved.

**Comment by bsutton** [comment]
will not proceed.
